# sweep_config.yaml
program: fine_tuning.py
method: random  # bayes, random, o grid
metric:
  name: eval/loss
  goal: minimize

name: qwen3-toolcalling-lora

parameters:
  # Learning rate 
  learning_rate:
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-3
  
  # LoRA rank 
  lora_r:
    values: [8, 16, 32]
  
  # LoRA alpha - Usually set to lora_r * n
  lora_alpha:
    values: [16, 32, 64]
  
  # Epochs
  num_train_epochs:
    values: [1, 2, 3]
  
  gradient_accumulation_steps:
    values: [8, 16, 32]
  
  max_batch_size:
    value: 32
  
  # Dropout
  lora_dropout:
    distribution: uniform
    min: 0.05
    max: 0.15
  
  # Warmup
  warmup_ratio:
    values: [0.05, 0.1, 0.15]

  # Export options
  export_to_q8:
    value: true # Whether to export the best model to 8-bit GGUF format 
  export_to_q4:
    value: false  # Whether to export the best model to 4-bit GGUF format 

run_cap: 15